apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-api
  template:
    metadata:
      labels:
        app: first-api
    spec:
      containers:
      - name: first-api
        image: first-api:v1
        ports:
        - containerPort: 8000