apiVersion: apps/v1
kind: Deployment
metadata:
  name: lte-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lte-api
  template:
    metadata:
      labels:
        app: lte-api
    spec:
      containers:
      - name: lte-api
        image: my-lte-api:v1
        ports:
        - containerPort: 8000
